---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker build -t $${NAME}:$${DRONE_COMMIT_SHA} .
  environment:
    DOCKER_HOST: tcp://127.0.0.1:2375
    NAME: proxy

- name: push_image_master
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - FULL_NAME=$${REPO}$${BASE}$${NAME}
  - docker login -u="$${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} $${REPO}
  - docker tag $${NAME}:$${DRONE_COMMIT_SHA} $${FULL_NAME}:$${DRONE_TAG}
  - docker tag $${NAME}:$${DRONE_COMMIT_SHA} $${FULL_NAME}:latest
  - docker push $${FULL_NAME}:$${DRONE_TAG}
  - docker push $${FULL_NAME}:latest
  environment:
    BASE: /ukhomeofficedigital/
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+proxy
    NAME: proxy
    REPO: quay.io
  when:
    event:
    - push

- name: push_image_tag
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - FULL_NAME=$${REPO}$${BASE}$${NAME}:$${DRONE_COMMIT_SHA}
  - docker login -u="$${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} $${REPO}
  - docker tag $${NAME}:$${DRONE_COMMIT_SHA} $${FULL_NAME}
  - docker push $${FULL_NAME}
  environment:
    BASE: /ukhomeofficedigital/
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+proxy
    NAME: proxy
    REPO: quay.io
  when:
    event:
    - tag

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
