pipeline:

  build_image:
    image: docker:17.09.0-ce
    environment:
      - NAME=proxy
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t $${NAME}:$${DRONE_COMMIT_SHA} .

  push_image_master:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - NAME=proxy
      - REPO=quay.io
      - BASE=/ukhomeofficedigital/
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_USERNAME=ukhomeofficedigital+proxy
    commands:
      - FULL_NAME=$${REPO}$${BASE}$${NAME}
      - docker login -u="$${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} $${REPO}
      - docker tag $${NAME}:$${DRONE_COMMIT_SHA} $${FULL_NAME}:$${DRONE_COMMIT_SHA}
      - docker tag $${NAME}:$${DRONE_COMMIT_SHA} $${FULL_NAME}:latest
      - docker push $${FULL_NAME}:$${DRONE_COMMIT_SHA}
      - docker push $${FULL_NAME}:latest
    when:
      branch: master
      event: push

  push_image_tag:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - NAME=proxy
      - REPO=quay.io
      - BASE=/ukhomeofficedigital/
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_USERNAME=ukhomeofficedigital+proxy
    commands:
      - FULL_NAME=$${REPO}$${BASE}$${NAME}:$${DRONE_TAG}
      - docker login -u="$${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} $${REPO}
      - docker tag $${NAME}:$${DRONE_COMMIT_SHA} $${FULL_NAME}
      - docker push $${FULL_NAME}
    when:
      event: tag
